name: Deploy React App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Zip Build Folder
        run: zip -r dist.zip dist/

      - name: Set Node.js Version for Web App
        run: az webapp config set --resource-group MyResourceGroup --name smxmusegrid --linux-fx-version "NODE|18-lts"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: smxmusegrid
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: dist.zip
