name: Deploy FastAPI Backend to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r backend/requirements.txt

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Python Version for Web App
        run: az webapp config set --resource-group MyResourceGroup --name smxmusegrid --linux-fx-version "PYTHON|3.9"

      - name: Set Startup Command
        run: az webapp config set --resource-group MyResourceGroup --name smxmusegrid --startup-file "uvicorn main:app --host=0.0.0.0 --port=8000"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: smxmusegrid
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
          package: backend/




